### ISSUE TITLE
Exception Info: System.NotImplementedException

### ISSUE THREAD

**Issue by masshendro** [sskodje/ScreenRecorderLib#88]
Hi,
The sample is working well on development machine but After I publish using clickonce and install to another windows 10 pro machine the apps not showing when i try to execute and when i check the event viewer : 

Source : .Net Runtime
Application: TestApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotImplementedException
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType, Int16)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at TestApp.App.Main()

Source : Application Error
Faulting application name: TestApp.exe, version: 1.0.0.0, time stamp: 0x5f662ce9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x5b4a3325
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0xa08
Faulting application start time: 0x01d68ea024eaf684
Faulting application path: C:\Users\masshendro\AppData\Local\Apps\2.0\OPMXQKLB.KDB\OQTB6D2Y.XNQ\test..tion_9fc5855391c42c6c_0001.0000_f93eaac8710230a3\TestApp.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0134c1cb-3500-4a26-bf52-92ddcd8bbe36
Faulting package full name: 
Faulting package-relative application ID: 

Information : 
Fault bucket 1439272336706208615, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: TestApp.exe
P2: 1.0.0.0
P3: 5f662ce9
P4: PresentationFramework
P5: 4.8.4220.0
P6: 5f03b15f
P7: fce
P8: 5b
P9: System.Windows.Markup.XamlParse
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB726.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBE0D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBE5C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBE89.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF07.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TestApp.exe_9bb0608f97d8fb51bf07d1d418a8ef99b66ef9_96038b8a_b415c253-c40d-4200-92fa-a2ebf99ca4ba

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0134c1cb-3500-4a26-bf52-92ddcd8bbe36
Report Status: 268435456
Hashed bucket: c960529e0edcb2eea3f952908c6b8367
Cab Guid: 0

**Comment by sskodje** [comment]
This error means there most likely is a missing dependency. Check if all the files are deployed on the other machine.

**Comment by masshendro** [comment]
Do you mean like this ?
![image](https://user-images.githubusercontent.com/71563099/93686341-cf40c180-fadf-11ea-9404-6925169cf48c.png)

**Comment by sskodje** [comment]
Looks like all the necessary files are there. I suggest using http://www.dependencywalker.com/ to see what it can't load.

**Comment by masshendro** [comment]
Hi,

i try to use dependencywalker : 

![image](https://user-images.githubusercontent.com/71563099/93693511-e8bb2b00-fb2a-11ea-8572-975ceef82f7e.png)

but this is the first i'm using dependencywalker. can you help me?

**Comment by sskodje** [comment]
Unfortunately depwalker always shows some system files missing that is not part of the problem. The easiest way to check is to run it on your development machine where you know it works, then run it on the other machine and see the difference.

**Comment by masshendro** [comment]
Hi,

I found the problems, i have to install Microsoft Visual C++ Redistributable 2015-2019 on Client. 

Thanks A lot for you response and support...
